name: Coding Standards

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ESLint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: ESLint check
        run: npm run lint

  Prettier:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Prettier check
        run: npm run format:check
