name: Staging Deployment
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.0.0

        env:
          SSH_BUILD_DIRECTORY: ${{ secrets.UAT_SSH_BUILD_DIRECTORY }}
          SSH_POST_BUILD_SCRIPT: post_build_script.sh

        with:
          host: ${{ secrets.UAT_SSH_HOST }}
          username: ${{ secrets.UAT_SSH_USERNAME }}
          key: ${{ secrets.UAT_SSH_PRIVATE_KEY }}
          envs: SSH_BUILD_DIRECTORY,SSH_POST_BUILD_SCRIPT

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'

      - name: Pulling latest code
        run: git checkout -f
          git pull origin main

      - name: Clean the cache
        run: npm cache clean --force

      - name: Install Project Dependencies
        run: npm install

      - name: Build
        run: npm run build
